version: 2
updates:
  # pnpm projects are configured with the npm ecosystem in Dependabot.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase-if-necessary"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
